site_name: PyAgentic Documentation

repo_name: rmikulec/pyAgentic
repo_url: https://github.com/rmikulec/pyagentic

nav:
  - Home: index.md
  - User Guide:
    - Getting Started: getting-started.md
    - Inheritance: inheritance.md
    - Agent Linking: agent-linking.md
    - Responses: responses.md
    - Structured Outputs: structured-output.md
    - Observability: observability.md
  - API Reference:
      - Modules: reference/modules.md

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            show_source: true
            source_link: true
            source_repository: "https://github.com/rmikulec/pyAgentic"
            source_branch: "main"  # or "master" or any branch you use
            source_directory: "pyagentic"
            members: true
            filters:
              - "!^__.*__$"  # Regex to exclude __dunder__ methods
            # Show init args as class signature
            show_signature: true
            show_signature_annotations: true
            merge_init_into_class: true
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - markdown.extensions.md_in_html
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - attr_list
  - md_in_html
  - def_list

theme:
  name: material
  features:
    - content.code.copy
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.highlight
    - search.share
  palette:
    - scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
