name: Release

on:
  push:
    # stable on main, beta on beta branch, and any v*.*.* tag
    branches:
      - 'main'
      - 'feat/**'
      - 'bug/**'
      - 'fix/**'

jobs:
  semantic-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0         # need full history for tags

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install uv
        run: python -m pip install --upgrade pip uv

      - name: Install dependencies
        run: uv sync --group dev

      - name: Run semantic-release
        env:
          PYPI_API_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
        run: uv run semantic-release publish
